[project]
authors = ["Paul Link <paullink65@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "test_repo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pytest = ">=8.3.5,<9"
black = ">=25.1.0,<26"
pre-commit = ">=4.2.0,<5"

[pypi-dependencies]
test_repo = { path = ".", editable = true }
